# Esprit Internship 2 Kubernetesfile

---

#  Database PersistentVolume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: esprit-internship2-pv-db
  labels:
    app: label-esprit-internship2-pv-db
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: esprit-internship2-scn-db
  hostPath:
    path: /mnt/data/esprit-internship2-db

---

# Database PersistentVolumeClaim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esprit-internship2-pvc-db
  labels:
    app: label-esprit-internship2-pvc-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: esprit-internship2-scn-db

---

# Backend + Database Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: esprit-internship2-dep-db-back
  labels:
    app: label-esprit-internship2-dep-db-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-esprit-internship2-dep-db-back
  template:
    metadata:
      labels:
        app: label-esprit-internship2-dep-db-back
    spec:
      containers:
      - name: esprit-internship2-dep-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
        ports:
        - containerPort: 3306
          name: cport-3306
        volumeMounts:
        - name: esprit-internship2-vol-db
          mountPath: /var/lib/mysql

      - name: esprit-internship2-dep-back
        image: mdjdocker/esprit-internship2-back:latest
        ports:
        - containerPort: 9000
          name: cport-9000
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 20
          failureThreshold: 3

      restartPolicy: Always

      volumes:
      - name: esprit-internship2-vol-db
        persistentVolumeClaim:
          claimName: esprit-internship2-pvc-db

---

# Backend NodePort Service

apiVersion: v1
kind: Service
metadata:
  name: esprit-internship2-nser-back
  labels:
    app: label-esprit-internship2-nser-back
spec:
  selector:
    app: label-esprit-internship2-dep-db-back
  ports:
  - port: 9000
    name: port-9000
    targetPort: 9000
    nodePort: 30001
  type: NodePort

---

# Frontend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: esprit-internship2-dep-front
  labels:
    app: label-esprit-internship2-dep-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-esprit-internship2-dep-front
  template:
    metadata:
      labels:
        app: label-esprit-internship2-dep-front
    spec:
      containers:
      - name: esprit-internship2-front
        image: mdjdocker/esprit-internship2-front:latest
        ports:
        - containerPort: 80
          name: cport-80
      restartPolicy: Always

---

# Frontend NodePort Service

apiVersion: v1
kind: Service
metadata:
  name: esprit-internship2-nser-front
  labels:
    app: label-esprit-internship2-nser-front
spec:
  selector:
    app: label-esprit-internship2-dep-front
  ports:
  - port: 80 
    name: port-80
    targetPort: 80
    nodePort: 30002
  type: NodePort

---
