FROM openjdk:17
WORKDIR /app
COPY "target/esprit-internship2-back-0.0.1-SNAPSHOT.jar" "esprit-internship2-back-0.0.1-SNAPSHOT.jar"
EXPOSE 9000
CMD ["java", "-jar", "esprit-internship2-back-0.0.1-SNAPSHOT.jar"]